### ISSUE TITLE
the QR code is not visible where it should be

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-app#102]
**Explanation**

When entering the profile, the QR code is not where it should be, it is below the expiration date of the membership

**Current**
![WhatsApp Image 2022-09-19 at 10 22 40 AM](https://user-images.githubusercontent.com/4030477/191053711-f5fd4af1-2a0a-448b-a72b-760534e217fa.jpeg)

**Expected result**
![image](https://user-images.githubusercontent.com/4030477/191053071-06303176-c451-4851-b909-abf2cf228ee6.png)

- [ ] locate the QR according to the design

**Comment by heliomar-pena** [comment]
I'd suggest EE 1 or 2

It's maybe a problem with responsive, what's your phone screen's size?
