### ISSUE TITLE
Button click action to return to previous view

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-app#103]
**Explanation**

when i go into the views and hit the back button it should work when clicking on the word and not just the back arrow
this happens in

- Event details
- calendar view
- product detail

![WhatsApp Image 2022-09-19 at 10 31 02 AM](https://user-images.githubusercontent.com/4030477/191056531-bcc17297-f2cf-4c20-b089-4f7e7fc660f7.jpeg)
![WhatsApp Image 2022-09-19 at 10 31 13 AM](https://user-images.githubusercontent.com/4030477/191056537-49c8a17b-e5f1-4430-b403-596515a6db22.jpeg)
![WhatsApp Image 2022-09-19 at 10 31 23 AM](https://user-images.githubusercontent.com/4030477/191056539-4285c0a5-6fa8-4541-8724-83fe3f0ee00b.jpeg)

- [ ] Clicking on the word and on the button takes me to the previous view in those views

**Comment by heliomar-pena** [comment]
I'd suggest EE 1 or 2

**Comment by Eghinner** [comment]
could you check if it was not resolved here https://github.com/Azordev/did-app/pull/84?

**Comment by heliomar-pena** [comment]
> could you check if it was not resolved here #84?

That PR have just solved the problem in Calendar and Events view
