### ISSUE TITLE
image icon used when there is no bad image

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-app#104]
Explanation

When entering the product detail and the user does not have a photo of that product, the image that is in the design must appear and not the white logo

**Current**
![imagen](https://user-images.githubusercontent.com/66505715/191087314-fea9838d-6738-44e2-83d6-710ed2b825cb.png)

**Expected result**
![imagen](https://user-images.githubusercontent.com/66505715/191087402-42c86b7f-7c1c-4122-b411-a0f510981e51.png)

**Comment by heliomar-pena** [comment]
I'd suggest EE 1

**Comment by Eghinner** [comment]
https://github.com/Azordev/did-admin-panel/blob/dev/views/SVGs/Picture/index.tsx

suggest
