### ISSUE TITLE
Develop Main Login View  /  Desarrollar Vista Principal Del Login

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#13]
**Explanation:**

  The main login view will be based on different sections. The image of DID Peru, message to enter DID Peru, the user field; which will be filled by the user who wishes to enter the application, password field, which will be filled in the same way by the user who wishes to enter the application. Also, enter the button. This button must be locked while the data entered is validated against the database. Besides; "Did you forget your password?" button. In addition to this, the "Associate with DID" button.

**User Stories to Fulfill:*

- [x] As a member, I want to place my username to be able to access my account.
- [x] As a member, I would like to enter a password to access my account.
- [ ] As a user, I would like to see the contact details of DID to acquire a membership.
- [ ] As a user, I would like to be able to reset my password.
- [ ] As a user, I want to be shown a support contact to reset my password.
- [x] As a user, I would like to see the "DID Peru" logo to be able to identify the app.
- [x] It has the message "Enter DID Peru"

### Dependencies:
It has no dependencies.

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/680ef50a-1656-43b7-ba65-e8b47775004c?hints=off

### Screenshot:
![DID 2](https://user-images.githubusercontent.com/98891182/170328165-0d69db01-cf8a-4be2-ade5-5e0a97b79ec1.png)

### Workflow:
There is no workflow because it is the main screen.

Spanish Version:

**Explicación:**

La vista principal de acceso estará basada en diferentes secciones. La imagen de DID Perú, mensaje de ingresar a DID Perú, el campo de usuario; el cual será llenado por el usuario que desee ingresar a la aplicación, campo de contraseña, que será llenado de igual manera por el usuario que desea ingresar a la aplicación. También, el botón de ingresar. Este botón deberá ser bloqueado mientras se validan los datos ingresados con la base de datos. Así mismo; botón de "¿Olvidaste tu contraseña?". Adicional a esto, el botón de "Asociarme a DID".   

**Historias de Usuario a Cumplir:*

- [x]  Como miembro, deseo colocar mi usuario para poder acceder a mi cuenta.
- [x] Como miembro, me gustaría colocar una contraseña para acceder a mi cuenta.
- [ ] Como usuario, quisiera ver los datos de contacto de  DID para adquirir una membresía.
- [ ] Como usuario, me gustaría poder reestablecer mi contraseña.
- [ ] Como usuario, deseo que se me muestre un contacto de soporte para reestablecer mi contraseña. 
- [x] Como usuario, me gustaría ver el logo de "DID Perú" para poder identificar la app.
- [x] Cuenta con el mensaje de "Ingresa a DID Perú" 
 
### Dependencias:
No tiene dependencias.

### Referencias
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/680ef50a-1656-43b7-ba65-e8b47775004c?hints=off

### Captura de pantalla:
![DID 2](https://user-images.githubusercontent.com/98891182/170328234-47591778-4e8c-4643-822f-2c9ed6061712.png)

### Flujo de trabajo:
No existe flujo de trabajo debido a que es pantalla principal.

**Comment by angelik0828** [comment]
1. the number of words used could be reduced, that is, make a simpler list of what will be seen in the view, since it is visualized a little extensive. 

2. I think that the user story is very extensive we could rely on the graphic resource to show the idea and not place so much text when mentioning in which part the elements go.

3. I think point 7 could be mentioned and placed in detail in another story as it is an element that leads to another view.

**Comment by CARPER11** [comment]
he realizado modificacion de la explicacion, sin embargo las historias es dificil modificarlas porque no cumpliria con los requisitos. no se que opinas @angelik0828
