### ISSUE TITLE
Create Home Screen View  /  Crear Vista De Pantalla Principal

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#14]
**Explanation:**

The view of the main screen is composed of 3 Layout or Designs that must show the user the following:
At the top the Design or User Design:
1- A welcome message with your registration name Ex: "Hello so-and-so".
2- Your unique registration code generated by the system.
3- The expiration date of your membership.
4- A Random or Random image, which will be located in the upper right.

In the center the Layout of events and suppliers:
1- The available events with image and date, in Carousel format.
2- "See more" button, which will allow access to the complete list of events.
3- DID providers which will be shown with an image or logo of them.
4- The "See more" button, to be able to see the providers in detail.

In the Footer or Scroll Buttons:
1- Scroll button to events.
2- Scroll button to providers.
3- Home scroll button.

**User stories to fulfill:**

- [x] As a user, I would like to see a text with my registration name.
- [x] As a member, I would like to see my unique registration code.
- [x] As a member, I want to know the expiration date of my membership.
- [x] As a member, I would like to be able to change my profile picture.
- [x] As a member, I want to know what events are available.
- [x] As a member, I need to know the date of the event.
- [x] As a member, I would like to be able to see a list of available events.
- [x] As a member, I want to see the providers that belong to DID.
- [x] As a member, I would like to see the logo of the providers that belong to DID in order to identify them.
- [x] As a member, I would like a button to be able to see the detailed information of the providers that belong to DID.
- [x] As a member, I need a button to be able to go to the events.
- [x] As a member, I would like to have a button to be able to go to the providers.
- [x] As a member, I would like a button to be able to go to the main screen.

### Dependencies:

It has no dependencies.

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc/?hints=off

### Screenshot:
![DID 3](https://user-images.githubusercontent.com/98891182/170119411-d090b070-d9ce-402e-a583-41681505a35b.png)

Spanish Version:

**Explicación:**

La vista de pantalla principal está compuesta por 3 Layout o Diseños que  deben mostrarle al usuario lo siguiente:
En la parte superior el Layout o Diseño de usuario:
1- Un mensaje de bienvenida con su nombre de registro Ej: "Hola fulanito".
2- Su código único de registro generado por el sistema.
3- La fecha de caducidad de su membresía.
4- Una imagen de perfil standard, la cual se ubicará en la parte superior derecha.

En el centro el Layout o diseño de eventos y proveedores:
1- Los eventos disponibles con una imagen y fecha, en formato Carrusel.
2- Botón de "Ver más", que permitirá acceder a la lista completa de eventos.
3- Los proveedores de DID los cuales se mostrarán con una imagen o logo del mismo.
4- El botón de "Ver mas", para poder ver los proveedores en detalle.

En el Footer o Pie de página o Botones de desplazamiento para un menú inferior fijo que permita la navegación, el orden debe ser, botón de inicio, botón de eventos y botón de proveedores:
1- Botón de desplazamiento hacia eventos.
2- Botón de desplazamiento hacia proveedores.
3- Botón de desplazamiento hacia inicio.

**Historias de usuario a cumplir:**

- [x] Como usuario, me gustaría ver un texto con mi nombre de registro.
- [x]  Como miembro, quisiera ver mi código único de registro.
- [x] Como miembro, quisiera conocer la fecha de caducidad de mi membresía.
- [x] Como miembro, quisiera poder cambiar la imagen de mi perfil.
- [x] Como miembro, deseo conocer los eventos disponibles.
- [x] Como miembro, quisiera conocer la fecha del evento.
- [x] Como miembro, me gustaría poder ver una lista de eventos disponibles.
- [x] Como miembro, deseo ver los proveedores que pertenecen a DID.
- [x] Como miembro, me gustaría ver el logo de los proveedores que pertenecen a DID para poder identificarlos.
- [x] Como miembro, desearía un botón para poder ver la información en detalle de los proveedores que pertenecen a DID.
- [x] Como miembro, quisiera un botón para poder dirigirme hacia los eventos.
- [x] Como miembro, me gustaría disponer de un botón para poder dirigirme hacia los proveedores.
- [x] Como miembro, quisiera un botón para poder dirigirme a la pantalla principal.

**Lista de verificación de casos de uso QA:**
- [ ]

**Lista de verificación tareas técnicas**
- [ ]

### Dependencias:

No tiene dependencias.

### Referencia:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc/?hints=off

### Captura de pantalla:
![did 3](https://user-images.githubusercontent.com/98891182/167988404-ac153df6-2700-45e9-843c-82c8789028fa.png)

**Comment by angelik0828** [comment]
@CARPER11  
![image](https://user-images.githubusercontent.com/4030477/168635246-410736ee-f383-49c2-8dc1-dac0aa65a828.png)

in this number 4 I think you could say that it is the profile image, the one that has been uploaded before or a random one will be shown.

I think item 2 of the list: In the center the Layout of events and suppliers, and the 4 transmit the same talk about the button to see more and could be put in one.

![image](https://user-images.githubusercontent.com/4030477/168633572-7a2c36e2-f81e-4493-8449-1c7eea828d6f.png)

this could be lower menu because it must be fixed on the page and allow navigation, the order of the items is also important.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by CARPER11** [comment]
> @CARPER11 ![image](https://user-images.githubusercontent.com/4030477/168635246-410736ee-f383-49c2-8dc1-dac0aa65a828.png)
> 
> in this number 4 I think you could say that it is the profile image, the one that has been uploaded before or a random one will be shown.
> 
> I think item 2 of the list: In the center the Layout of events and suppliers, and the 4 transmit the same talk about the button to see more and could be put in one.
> 
> ![image](https://user-images.githubusercontent.com/4030477/168633572-7a2c36e2-f81e-4493-8449-1c7eea828d6f.png)
> 
> this could be lower menu because it must be fixed on the page and allow navigation, the order of the items is also important.

make the pertinent modifications taking into account the suggestions. Thank you

**Comment by angelik0828** [comment]
@victor-heliomar  perform review, you need:
1) The calendar button disappears.
2) add button see more in events and suppliers.
3) when membership expires remove events and vendors or show nothing

**Comment by heliomar-pena** [comment]
Done! please check here https://did-app.netlify.app/
