### ISSUE TITLE
Password Reset and Membership Acquisition Screen  /  Pantalla De Restablecimiento De Contraseña Y Adquisición De Membresía

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#15]
**Explanation:**

For password reset in the DID app, a message with support contact information should be displayed for the user to initiate the password reset process. In the same way, for the acquisition of the membership, the contact information must be shown to start the process of purchasing the membership. For this, a functional support screen must be created for both cases since the contact details will be the same. The Login button must be locked while data is being validated. Besides; a message should be displayed to the user if their password or username is invalid, for example: "Wrong password".

**User Stories to fulfill:**

- [ ] As a member, I want to place my username to be able to access my account.
- [ ] As a member, I want to enter a password to access my account.
- [ ] As a member, I would like to be informed when my username or password to access the platform is not valid.
- [ ] As a member, I want to press a button to access the application.
- [ ] The Login button is blocked while the data is validated.

### Dependencies:

- [ ] #13

### References:

Spanish Version:

**Explicación:**

Para el restablecimiento de contraseña en DID app, se deberá mostrar un mensaje con la información de contacto a soporte para que el usuario inicie su proceso de restablecimiento de contraseña. De igual manera, para la adquisición de la membresía se deberá mostrar la información de contacto para iniciar el proceso de compra de la membresía. Para ello se deberá crear una pantalla de soporte funcional para ambos casos ya que la información de contacto será la misma. El botón de Login debe bloquearse mientras se validan los datos. Así mismo; se debe mostrar un mensaje al usuario si su contraseña o nombre de usuario es inválido. Ej: “Contraseña incorrecta”.

**Historias de usuario a cumplir:**

- [ ]  Como miembro, quiero colocar mi usuario para poder acceder a mi cuenta.
- [ ] Como miembro, quiero colocar una contraseña para acceder a mi cuenta.
- [ ] Como miembro, quisiera que se me indique cuándo no sea válido mi usuario o contraseña para acceder a la plataforma.
- [ ] Como miembro, quiero pulsar un botón para acceder a la aplicación.
- [ ] El botón de Login se bloquea mientras se validan los datos.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:

- [ ] #13

**Comment by anaceciliamolinares** [comment]
No veo las referencias si es que las hay.

**Comment by e-azocar** [comment]
> No veo las referencias si es que las hay.

@anaceciliamolinares no hay referencias

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
This task don't make sense to me, or maybe the description is not clear? Please check if can be closed
