### ISSUE TITLE
User Design  /  Diseño De Usuario

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#16]
**Explanation:**

This Layout or Design is designed to fulfill the function of allowing the user to quickly view the registration information within the platform, such as their unique registration code, a welcome greeting, such as: "Hello (and the name of the user), expiration membership date and status, it will also have an icon that will direct the user to their profile where they can make changes to it.

**User Stories to fulfill:**

- [x] As a member, I want to see my unique registration code.
- [x] As a member, I would like to go to my profile.
- [x] As a member, I would like to go to my profile.
- [x] As a member, I would need to see the expiration date of my membership.
- [x] As a member, I want to see the status of my membership.

### Dependencies:
It does not have any.

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc/?hints=off

### Screenshot:
![DID 3](https://user-images.githubusercontent.com/98891182/170116232-29793f4d-6b2f-4d8f-9e7b-a50a2e384e87.png)

### workflow
Access – Main Screen.

Spanish Version:

** Explicación:**

Este Layout o Diseño está pensado para cumplir la función de permitirle al usuario visualizar de manera rápida la información de registro dentro de la plataforma, como su código único de registro, un saludo de bienvenida, como por ej.: “Hola (y el nombre del usuario), fecha de caducidad de la membresía y el status de la misma. Además contará con un ícono que dirigirá al usuario a su perfil donde podrá realizar modificaciones al mismo.

**Historias de usuario a cumplir:**

- [x]  Como miembro, deseo ver mi código único de registro.
- [x] Como miembro, me gustaría dirigirme a mi perfil.
- [x] Como miembro, quisiera ver un saludo de bienvenida.
- [x] Como miembro, necesitaría ver la fecha de caducidad de mi membresía.
- [x] Como miembro, deseo ver el estatus de mi membresía.
- [x] #32

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:
No tiene.

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc/?hints=off

### Captura de pantalla:
![DID 3](https://user-images.githubusercontent.com/98891182/170116355-38cd1c6b-32b0-4384-9e6a-3195116fc9be.png)

### Flujo de trabajo:
Acceso – Pantalla Principal.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
done
