### ISSUE TITLE
Event Design and Providers  /  Diseño De Eventos y Proveedores

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#17]
**Explanation:**

This layout or design is made up of two sections:
1- carousel type view of the events planned by DID. These events must show an image of the event, title of the event and the date of the event. Also the "See more" button, which should redirect the user to a list view of events.
2- supplier view must show the suppliers in Carousel format, in which we can see the logos of the suppliers belonging to DID and must have a "See more" button. This button will allow the user to go to the providers view.

**User stories to fulfill:**

- [x] As a member, I want to see the available events.
- [x] As a member, I need to see the date of available events.
- [x] As a member, I would like to see an image of the event available.
- [x] As a member, I need to have a button to go to an event list view.
- [x] As a member, I would like to see the logos of DID providers.
- [x] As a member, I would like a button to direct me to see the providers in detail.

### Dependencies:
Does not have any.

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc?
hints=off

### Screenshot:
![DID 3](https://user-images.githubusercontent.com/98891182/170083217-8945a399-56bf-408c-994e-4406b0997e0a.png)

### Workflow:
Access– Main Screen.

Spanish Version:

**Explicación:**

Este layout o diseño está compuesto por dos secciones: 
1- vista tipo carrusel de los eventos planificados por DID. Estos eventos deben mostrar una imagen del evento, título del evento y la fecha del mismo. También el botón de "Ver más", el cual deberá redirigir al usuario a una vista de lista de eventos. 
2- vista de proveedores deberá mostrar los proveedores en formato Carrusel, en el cual podremos ver los logos de los proveedores pertenecientes a DID y debe contar con un botón de "Ver más". Este botón le permitirá al usuario dirigirse a la vista de proveedores.

**Historias de usuario a cumplir:**

- [x]  Como miembro, deseo ver los eventos disponibles.
- [x] Como miembro, necesito ver la fecha de los eventos disponibles.
- [x] Como miembro, me gustaría ver una imagen del evento disponible.
- [x] Como miembro, necesito tener un botón para dirigirme a una vista de lista de eventos.
- [x] Como miembro, me gustaría ver los logos de los proveedores de DID.
- [x] Como miembro, quisiera un botón para dirigirme a ver de manera detallada los proveedores.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:
No tiene

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc?hints=off

### Captura de pantalla:
![DID 3](https://user-images.githubusercontent.com/98891182/170083611-46781f86-e578-4ae3-b812-ed73951ebf1d.png)

### Flujo de trabajo:
Acceso– Pantalla Principal.

**Comment by anaceciliamolinares** [comment]
CARPER11, en la explicación se dice que está compuesta por 2 secciones. Puedes enumerar cuáles son? Lo veo un poco confuso, pues hay varios detalles y no se sabe a cuál de las 2 secciones se refiere. Gracias.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
This task is done, please check here: https://did-app.netlify.app/
