### ISSUE TITLE
Navigation Bar  /  Barra De Navegacion

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#18]
**Explanation:**

The navigation bar is intended to allow the user to scroll between views, ie; 3 buttons must be created, 1- The start button, 2- The events button 3- The suppliers button. These buttons should locate the user in the mentioned views, for example, the providers button should direct the user to the detailed providers section. These buttons will be located at the bottom of the view.

**User stories to fulfill:**

- [x] As a member, I would like to be able to switch views using scroll buttons.
- [x] As a member, I would like to be able to go to the events list through a button.
- [x] As a member, I want to be able to go to the list of providers through a button.
- [x] As a member, I want to be able to go to the start via a button.

### Dependencies:
It does not have any.

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc?hints=off

### Screenshot:
![DID 3](https://user-images.githubusercontent.com/98891182/170080925-72d25733-95a6-4a91-b2d3-a3d9558c4a84.png)

### Workflow:
Access– Main Screen- Events.
Access- Main Screen- Providers.
Access- Main Screen- Events- Home.

Spanish Version:

**Explicación:**

La barra de navegación está pensada para permitir al usuario desplazarse entre vistas, es decir; que deberán crearse 3 botones, 1- El botón de inicio, 2- El botón de eventos 3- El botón de proveedores. Estos botones deberán ubicar al usuario en las vistas mencionadas, por ejemplo, el botón de proveedores deberá dirigirlo a la sección detallada de proveedores. Estos botones se ubicarán en la parte inferior de la vista.

**Historias de usuario a cumplir:**

- [x]  Como miembro, me gustaría poder cambiar de vistas usando botones de desplazamiento.
- [x] Como miembro, quisiera poder dirigirme a la lista de eventos a través de un botón.
- [x] Como miembro, me gustaría poder dirigirme a la lista de proveedores a través de un botón.
- [x] Como miembro, desearía poder dirigirme al inicio a través de un botón.

**Checklist de casos de uso QA:**
- [x] Navegar en la aplicación desde el menú inferior,  al dar clic en inicio me llevara a esta sección
- [x] Navegar en la aplicación desde el menú inferior,  al dar clic en eventos me llevara a esta sección
- [x] Navegar en la aplicación desde el menú inferior,  al dar clic en proveedores  me llevara a esta sección

**Checklist tareas técnicas**
- [ ]

### Dependencias:
No tiene.

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc?hints=off

##Captura de pantalla
![DID 3](https://user-images.githubusercontent.com/98891182/170081044-4dee6c4f-5c56-4f64-86a3-56ec9def4072.png)

### Flujo de trabajo:
Acceso– Pantalla Principal- Eventos.
Acceso- Pantalla Principal- Proveedores.
Acceso- Pantalla Principal- Eventos- Inicio.

**Comment by angelik0828** [comment]
@CARPER11  I think calling it bottom menu or navigation bar is better

**Comment by CARPER11** [comment]
> @CARPER11 I think calling it bottom menu or navigation bar is better

Solved

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by angelik0828** [comment]
When entering the application it was validated that the menu was there, the icons are located at the bottom, when clicking on them I will:
1) Start
2) Events
3) Suppliers
![image](https://user-images.githubusercontent.com/4030477/175117852-59e6133b-18e6-4f0c-a4c3-d1d738ca0cd4.png)
