### ISSUE TITLE
Provider View  /  Vista De Proveedores

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#19]
** Explanation:**

The purpose of the supplier view is to allow the user to view the existing suppliers within DID, in addition to being able to locate the products they offer through a search bar or by category. This view has an image of the supplier's logo, a search bar and a filter by category, as well as a button to return to the home or main screen.

**User stories to fulfill:**

- [x] As a member, I would like to be able to view the providers that integrate DID.
- [x] As a member, I want to be able to search for providers by name.
- [ ] As a member, I want to be able to filter vendor products by category.
- [x] As a member, I would like to be able to go home via a button.

### Dependencies:
It does not have.

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/15f95131-2738-453e-97b7-95a8716cd097?hints=off

### Screenshot:
![DID 6](https://user-images.githubusercontent.com/98891182/170053112-b7f18323-8676-4d24-a398-649b0bb38751.png)

### Workflow:
Access- Main Screen- Providers.

Spanish Version:

**Explicación:**

La vista de proveedores tiene como finalidad permitirle al usuario visualizar los proveedores existentes dentro de DID, además de poder ubicar los productos que ofrecen por medio de una barra de búsqueda o por rubros. Esta vista cuenta con una imagen del logo del proveedor, una barra de búsqueda y un filtro por rubro, además de un botón para  volver al inicio o pantalla principal.

**Historias de usuario a cumplir:**

- [x]  Como miembro, me gustaría poder visualizar los proveedores que integran DID.
- [x] Como miembro, quiero poder buscar los proveedores por su nombre.
- [ ] Como miembro, deseo poder filtrar los productos de los proveedores por rubro.
- [x] Como miembro, quisiera poder dirigirme al inicio a través de un botón.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:
No tiene.
### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/15f95131-2738-453e-97b7-95a8716cd097?hints=off

### Captura de pantalla
![DID 6](https://user-images.githubusercontent.com/98891182/170052672-59dca8a6-e597-497c-8edc-8a99e12f71c5.png)

### Flujo de trabajo:
Acceso- Pantalla Principal- Proveedores.

**Comment by angelik0828** [comment]
@CARPER11  I think it would be necessary to describe what it would look like before performing a search and then with the search so that the programmer knows.

**Comment by CARPER11** [comment]
@Katsu08 Consideras necesario indicar en una historia la search bar?

[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by CARPER11** [comment]
@anaceciliamolinares realice un cambio en la hisotira de busqueda de "productos" a proveedores

**Comment by heliomar-pena** [comment]
> @Katsu08 Consideras necesario indicar en una historia la search bar?
> 
> [SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 [SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar [SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes. [SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar @anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar. Gracias de antemano.

Si, me parece que hacer funcionar la search bar puede tener su propia historia

**Comment by heliomar-pena** [comment]
I have problems with this issue:

- [ ] Como miembro, deseo poder filtrar los productos de los proveedores por rubro.

;( I don't know how to do the query to filter by provider category.

But I've worked on the other features.
