### ISSUE TITLE
Products View  /  Vista De Productos

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#20]
**Explanation:**

The product view has the function of showing the user the products that a specific supplier manufactures: the name of the product, its price, and a description of the product, an image of the product and a shopping cart to be able to add the product to it. In addition, in the layout or top design, you must show the name of the supplier, a button to go to the shopping cart and a button to go back.

**User stories to fulfill:**

- [x] As a member, I would like to know the products that a specific provider manufactures.
- [x] As a member, I would like to see the name of the product.
- [x] As a member, I want to know the price of the product.
- [x] As a member, I need to see an image alluding to the product.
- [x] As a member, I would like to have the name of the provider that offers the product.
- [x] As a member, I want to be able to add products to a shopping cart.
- [x] As a member, I need to see the products added to the shopping cart.
- [x] As a member, I would be necesary to have the option to go back from the product view.
 - [x] As a member, I would like to have a search bar to search for products by name.

### Dependencies:
It does not have.

###References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/218fa64a-8493-4335-9023-8409eb84ee92?hints=off

### Screenshot:
![DID 7](https://user-images.githubusercontent.com/98891182/170051507-91b10f03-0d20-4cd6-87a0-33e8decfd872.png)

### Workflow:
Access- Main Screen- Providers- Specific Provider.

Spanish Version:

**Explicación:**
La vista de productos tiene como función mostrarle al usuario los productos que fabrica un proveedor en especifico: el nombre del producto, su precio, y una descripción del producto, una imagen del producto y un carrito de compras para poder añadir el producto al mismo. Además, en el layout o diseño superior, deberá mostrar el nombre del proveedor, un botón para dirigirme al carrito de compras y un botón para volver atrás.

**Historias de usuario a cumplir:**

- [x]  Como miembro, quisiera conocer los productos que fabrica un proveedor en específico.
- [x] Como miembro, me gustaría ver el nombre del producto.
- [x] Como miembro, deseo conocer el precio del producto.
- [x] Como miembro, quisiera ver una imagen alusiva al producto.
- [x] Como miembro, me gustaría tener el nombre del proveedor que ofrece el producto.
- [x] Como miembro, quisiera poder añadir productos a un carrito de compras.
- [x] Como miembro, me gustaría ver los productos añadidos al carrito de compras.
- [x] Como miembro, quisiera tener la opción para volver atrás desde la vista del producto.
- [x] Como miembro, quisiera contar con una barra de búsqueda para buscar los productos por su nombre.

### Dependencias:
No tiene.

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/218fa64a-8493-4335-9023-8409eb84ee92?hints=off

### Captura de pantalla:
![DID 7](https://user-images.githubusercontent.com/98891182/170049864-10d3a195-8fdc-42c4-9219-e128979b9586.png)

### Flujo de trabajo:
Acceso- Pantalla Principal- Proveedores- Proveedor Específico.

**Comment by anaceciliamolinares** [comment]
CARPER11 En este Issue también faltan las dependencias.

**Comment by CARPER11** [comment]
> CARPER11 En este Issue también faltan las dependencias.

Solved

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by CARPER11** [comment]
@anaceciliamolinares he cargado una nueva historia de usuario

**Comment by heliomar-pena** [comment]
I think the shopping carts tasks should be on a Shopping Cart story.

Since currently isn't developed the Shopping Cart, I couldn't add products to the Shopping Cart

**Comment by heliomar-pena** [comment]
About this three tasks:

- [ ] As a member, I want to be able to add products to a shopping cart.
- [ ] As a member, I need to see the products added to the shopping cart.
- [ ] As a member, it would be necessary to have the option to go back from the product view.

I think the shopping cart functionality should be on the shopping card story

The go back from the product view I think it's invalid since the design doesn't have any way to go back from the product view.

If you mean when someone clicks on a detailed product, then that task should be on the detailed product story

**Comment by CARPER11** [comment]
> I think the shopping carts tasks should be on a Shopping Cart story.
> 
> Since currently isn't developed the Shopping Cart, I couldn't add products to the Shopping Cart

no problem I'll pass those stories to an issue

**Comment by CARPER11** [comment]
> About this three tasks:
> 
> * [ ]  As a member, I want to be able to add products to a shopping cart.
> * [ ]  As a member, I need to see the products added to the shopping cart.
> * [ ]  As a member, it would be necessary to have the option to go back from the product view.
> 
> I think the shopping cart functionality should be on the shopping card story
> 
> The go back from the product view I think it's invalid since the design doesn't have any way to go back from the product view.
> 
> If you mean when someone clicks on a detailed product, then that task should be on the detailed product story

I think what I did not do was explain myself well, I would have the option to go to the main screen and this would be achieved from the navigation bar, what do you think? @Katsu08

**Comment by heliomar-pena** [comment]
> I think what I did not do was explain myself well, I would have the option to go to the main screen and this would be achieved from the navigation bar, what do you think? @Katsu08

It seems to me that the milestone is fine, but currently, the navigation bar is not developed, currently, a navigation bar is seen below it but it is not the exact design haha, do you think it is fine for now until the navigation bar is developed correctly?

![image](https://user-images.githubusercontent.com/66505715/171024401-b81e85db-2e10-46e9-9b0d-4c85a9d494a4.png)

**Comment by heliomar-pena** [comment]
Added on #51
