### ISSUE TITLE
Product Detail View  /  Vista Detallada Del Producto

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#21]
**Explanation:**

With the same components of the product view, the product detail view seeks to offer the user detailed and complete information about the specific product of their preference. This view consists of the back button, product image, product price, product name, product description and the shopping cart to add the product to it.

**User stories to fulfill:**

- [x] As a member, I want to see the name of the product.
- [x] As a member, I want to know the price of the product.
- [x] As a member, I would like to see a description of the product.
- [x] As a member, I would like to see an image alluding to the product.
- [x] As a member, I would need to be able to add the product to a shopping cart.
- [x] As a member, I would like to have the option to go back from the product view.

### Dependencies:

It has no dependencies

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/cd2b953b-92b6-4048-942f-07a93014e7b4?hints=off

### Screenshot:
![DID8](https://user-images.githubusercontent.com/98891182/170047532-3cb9bd54-f582-4582-8a09-bb13485d7e88.png)

### Workflow:
Access- Main Screen- Providers- Specific Provider- specific product.

Spanish Version:

**Explicación:**

Con los mismos componentes de la vista de productos, la vista detalla de producto busca ofrecer al usuario una información detallada y completa sobre el producto en especifico de su preferencia. Esta vista se compone de el botón de volver atrás, la imagen del producto, el precio del producto, nombre del producto, descripción del producto y el carrito de compras para poder añadir el producto al mismo.

**Historias de usuario a cumplir:**

- [x] Como miembro, quiero ver el nombre del producto.
- [x] Como miembro, quiero conocer el precio del producto.
- [x] Como miembro, quisiera ver una descripción del producto.
- [x] Como miembro, quisiera ver una imagen alusiva al producto.
- [x] Como miembro, quisiera poder añadir el producto a un carrito de compras.
- [x] Como miembro, quisiera tener la opción para volver atrás desde la vista del producto.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:

No tiene dependencias.

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/cd2b953b-92b6-4048-942f-07a93014e7b4?hints=off

### Captura de pantalla:
![DID8](https://user-images.githubusercontent.com/98891182/170047700-e6b8990d-37e3-4019-abdc-72bb1c1c702c.png)

### Flujo de Trabajo:
Acceso- Pantalla Principal- Proveedores- Proveedor Específico- Producto Específico.

**Comment by anaceciliamolinares** [comment]
CARPER11 olvidaste colocar las dependencias.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
Added on #51
