### ISSUE TITLE
  Shopping Cart View

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#22]
**Explanation**

The shopping cart view is made up of 3 layouts, the top layout, the middle layout, and the bottom layout.
Top Layout – Will contain provider name and back button.

Central Layout: made up of the name of the items selected by the user, in addition, the user must be able to choose the quantity of the item they want, in the same way the price of each of the products must be expressed, this The section will have a maximum of 4 spaces for products.

Lower design: it will be made up of the total price of the order, and the verification button that will redirect the user to a WhatsApp chat with the supplier. 

**User stories to fulfill:**

- [x] As a member, I want to see the name of the product.
- [x] As a member, I want to know the price of the product.
- [x] As a member, I would like to see a description of the product.
- [x] As a member, I would like to see an image alluding to the product.
- [x] As a member, I would like to be able to add the product to a shopping cart.
- [x] as a member, I would like to have the option to go back from the product view.

### Dependencies

It does not have dependencies.

### References:
[
![did 11](https://user-images.githubusercontent.com/98891182/168244784-855bd279-5a85-42ed-8e6f-a6b98c9e9220.png)
](https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/a9a6efa6-bb63-4032-b058-b671683fb103?hints=off

### Screenshot:
![image](https://user-images.githubusercontent.com/66505715/174437873-60bcdb2a-deb9-4b44-85ee-060baab7e23e.png)

### Workflow:
Login-  Main Screen- Providers- Specific Provider- Specific Product- Shopping Cart.

Spanish Version:

**Explicación:**

La vista del carrito de compras se compone de 3 diseños, el diseño superior, el diseño medio y el diseño inferior.
Diseño superior: contendrá el nombre del proveedor y el botón Atrás.

Layout Central: conformado por el nombre de los artículos seleccionados por el usuario, además, el usuario debe poder elegir la cantidad del artículo que desea, de igual forma debe expresarse el precio de cada uno de los productos, esto La sección tendrá un máximo de 4 espacios para productos.

Diseño inferior: estará compuesto por el precio total del pedido, y el botón de verificación que redirigirá al usuario a un chat de WhatsApp con el proveedor.

**Historias de Usuario para cumplir:**

- [x] Como miembro, deseo ver el nombre del producto.
- [x] Como miembro, me gustaría saber el precio del producto.
- [x] Como usuario me gustaría ver los detalles de mi compra
- [x] Como usuario quisiera ver el precio por unidad del producto seleccionado
- [x] Como usuario quisiera saber el total de la compra que voy a realizar
- [x] Como usuario quisiera poder comunicarme con el proveedor.
- [x] Como usuario quisiera poder escoger la cantidad que desee del producto

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:

No tiene dependencias.

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/a9a6efa6-bb63-4032-b058-b671683fb103?hints=off

### Captura de pantalla:
![DID 9](https://user-images.githubusercontent.com/98891182/170163088-ce3c588a-e59a-472e-9c51-6f9e03039ba6.png)

### Flujo de trabajo:

Inicio de sesión- Pantalla Principal- Proveedores- Proveedor Específico- Producto Específico- Carrito de Compras.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios mayores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar y he cambiado algunas historias de usuario en correspondencia con la mejora de la vista.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
Added on #51
