### ISSUE TITLE
Loading Page  /  Cargando Página

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#24]
**Explanation:**

The "Loading page" has the objective of being the view that is shown to the user while the app is loading.

**User Stories to fulfill:**

- [ ] As a member, I would like to know when the app view is loading.

### Dependencies:

It has no dependencies.

### Screenshot:
![did 1](https://user-images.githubusercontent.com/98891182/168898052-f23d6e90-ff74-4eda-b43b-062180205db9.png)

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/?hints=off

### Workflow.
It does not have since it is the only view

Spanish Version:

**Explicación:**

La "Loading page", tiene el objetivo de ser la vista que se le muestre al usuario mientras la app está cargando.

**Historias de usuario a cumplir:**

- [ ]  Como miembro, quisiera saber cuando se este cargando la vista la app.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:

No posee dependencias.

### Captura de pantalla:
![did 1](https://user-images.githubusercontent.com/98891182/168898052-f23d6e90-ff74-4eda-b43b-062180205db9.png)

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/?hints=off

### Flujo de trabajo:
No posee, ya que es vista única.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
Added, I don't remember PR's number, but it appears in the APP as a Splashscreen
