### ISSUE TITLE
Button To Change Password  /  Botón Para Cambiar Contraseña

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#28]
**Explanation:**

The change password button should allow the user to make any desired change to the password.

**User Stories to fulfill:**
- [ ] As a user, I want to be able to change my password.

### Dependencies:
- [ ] https://github.com/Azordev/did-app/issues/27

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/eade16b8-2a30-4e26-ba61-475abecef71f?hints=off

### Screenshot:
![DID 10](https://user-images.githubusercontent.com/98891182/169927131-82557d92-7d5d-4750-9f6f-824cca57bf6a.png)

### Workflow:
Access-Main Mcreen- My Profile Button.

Spanish Version:

**Explicación:**

El botón de cambio de contraseña debe permitirle al usuario realizar la modificación que desee en la contraseña.

**Historias de usuario a cumplir:**
- [ ] Como usuario, deseo poder cambiar mi contraseña.

**Checklist de casos de uso QA:**
- [ ]
- 
**Checklist tareas técnicas**
- [ ]
### Dependencias:
- [ ] https://github.com/Azordev/did-app/issues/27

### Referencias: 
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/eade16b8-2a30-4e26-ba61-475abecef71f?hints=off

### Captura de pantalla:
![DID 10](https://user-images.githubusercontent.com/98891182/169926711-da8f7e01-bae5-460d-a5a3-3200e338d30b.png)
 

### Flujo de Trabajo:
Acceso-Pantalla Principal- Botón De Mi Perfil.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para completar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by CARPER11** [comment]
Me gustaria por favor alguna sugerencia para que el workflow sea mas notable y entendible apra el desarrollador. Gracias de antemano @angelik0828 @Katsu08 @e-azocar

**Comment by Eghinner** [comment]
there is no design for this part. First solve #27
