### ISSUE TITLE
Order List From Newest To Oldest And Vice Versa In The Event Display List  /  Ordenar Lista De Más Reciente A Más Antiguo Y Viceversa En la Lista De Vista De Eventos.

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#4]
**Explanation:**

At DID we seek to offer a fluid user experience and for this we want to offer the user the possibility of sorting the list of events through a drop-down list with two options:

1. From the most recent to the oldest.
2. From the oldest to the most recent.

**User stories to fulfill:**
- [ ] As a user, I want to use a dropdown list to order the events.
- [ ] As a user, I would like to see a dropdown list with options to sort the available events from recent to old and vice versa.

###Dependencies:
- [x] #3 

###Referencies:
It does not have.

Flujo de trabajo:
Access-Main Screen- Events.

Spanish Version:

**Explicación:**

En DID buscamos ofrecer una experiencia de usuario fluida. Para ello, queremos ofrecerle al usuario la posibilidad de ordenar la lista de eventos a través de una lista desplegable con dos opciones:
 
1. Desde los más recientes a los más antiguos. 
2. De los más antiguos a los más recientes.

**Historias de usuario a cumplir**

- [ ]  Como usuario, deseo usar una lista desplegable para que se ordenen los eventos.
- [ ] Como usuario, me gustaría ver una lista desplegable con opciones para ordenar los eventos disponibles de reciente a antiguo y viceversa.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:
- [x] #3 

### Referencias:
No posee.

### Flujo de trabajo:
Acceso-Pantalla Principal- Eventos.

**Comment by anaceciliamolinares** [comment]
CARPER11, lleva este issue alguna referencia como los demás?

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
The last design has removed this feature
![image](https://user-images.githubusercontent.com/66505715/178612052-c9cdf43d-83cd-4007-be20-890d0a7157bb.png)
