### ISSUE TITLE
Change Relative Routes For Alias ​​'src/' If Needed  /  Cambiar Las Rutas Relativas Para El Alias 'src/' En Caso De Ser Necesario

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/did-app#50]
## Explanation:

Some components are importing stuff using some like this:

```js
import { element } from '../../../utils/logger'
```

I would like to change it to:

```js
import { element } from 'src/utils/logger'
```

## Context:

_Originally posted by @Israel-Laguan at https://github.com/Azordev/did-app/pull/49#discussion_r901022890_

---

# Spanish Version:

## Explicación:

Algunos componentes están importando cosas, utilizando algunos como este:

```js
importar { elemento } desde '../../../utils/logger'
```

Me gustaría  cambiarlo por

```js
importar { elemento } desde 'src/utils/logger'
```

## Contexto:

_Publicado originalmente por @Israel-Laguan en https://github.com/Azordev/did-app/pull/49#discussion_r901022890_

**Comment by Israel-Laguan** [comment]
I think is EE1 or EE-2

**Comment by heliomar-pena** [comment]
Hmm I think 1, and if it's getting complicated (webpack errors or some like that) we can use EE-2
