### ISSUE TITLE
Styles For Home View - DID  /  Estilos Para La Vista De Inicio - DID

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-app#55]
### Explanation:

In this view, I checked but didn't find the styles shown in the original layout, at least the text ones:

1. The text used in the name and the "Hello" text is not correct. It should be: "Helvetica Now Text, Extra Bold"
2. The membership code uses the same "Helvetica Now Text, Regular".
3. Membership status does not have the font, nor should it handle: "Visby, Regular"
4. Membership expiration date text should be: "Helvetica Now Text, Regular"
5. The event text must have a different font: "Helvetica Now Text, Extra Bold"
6. The icon used in the "Calendar" button is different.
7. The icon used in the "User Profile" is different.

**Current result:**

The layout typography is not implemented in the application. The icon used in the "Calendar" button is different. The icon used in the user profile is different.

**Expected result:**

It is expected that when entering the app the original design and the appropriate fonts should be seen. Likewise, it is expected that the logo image adjusts to the size of the container in the events section. Likewise, the icons mentioned are expected to be correct.

The following changes will be made:

1. The text used in the name and the "Hello" text is not correct, it should be: "Helvetica Now Text, Extra Bold"
2. The membership code uses the same: "Helvetica Now Text, Regular."
3. Membership status does not have the source. You must also not drive: Visby, Regular
4. Membership expiration date text should be: "Helvetica Now Text, Regular".
5. The "Event" text must have a different font: "Helvetica Now Text, Extra Bold".
6. The icon used in the calendar button is different.
7. The icon used in the user profile is different. 
*Screen size:* (Full screen)

### Screenshots
![image](https://user-images.githubusercontent.com/4030477/175394595-6b40937a-5bf6-410c-8c50-94629a3032b9.png)
![image](https://user-images.githubusercontent.com/4030477/175394623-f0ab6af4-7942-4a4d-b776-5caeb9cb59f3.png)
![image](https://user-images.githubusercontent.com/4030477/175394654-cc7ceb88-86cd-4baa-b737-053c35a69a82.png)
![image](https://user-images.githubusercontent.com/4030477/175395114-b22a9cc8-8a69-4ed8-be9c-802d6dadf54d.png)
![image](https://user-images.githubusercontent.com/4030477/175396657-114fb671-e0e1-4f06-bad4-1c5a42e8f7d7.png)

Original

![image](https://user-images.githubusercontent.com/4030477/175398857-4860dd51-8e90-45ad-97b7-ce65d977c6fb.png)

### Check list:

- [ ] Change bold and regular fonts as appropriate.
- [ ] Change the icons of: Profile and Calendar.
- [ ] Verify that the items on the list of expectations are correct.

###References:
**Design:** https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc/specs/
 **Our:** https://deploy-preview-51--did-app.netlify.app/

---

# Spanish Version:

### Explicación:

En esta vista, verifiqué pero no encontré los estilos que se muestran en el diseño original, al menos los de texto:

1. El texto utilizado en el nombre y el texto "Hola" no es correcto. Debería ser: "Helvetica Now Text, Extra Bold"
2. El código de membresía usa el mismo "Helvetica Now Text, Regular".
3. El estado de la membresía no tiene la fuente, ni debe manejar: "Visby, Regular"
4. El texto de la fecha de vencimiento de la membresía debe ser: "Helvetica Now Text, Regular"
5. El texto del evento debe tener una fuente diferente: "Helvetica Now Text, Extra Bold"
6. El ícono utilizado en el botón de "Calendario" es diferente.
7. El ícono utilizado en el "Perfil de Usuario" es diferente.

**Resultado actual:**

La tipografía del diseño no está implementada en la aplicación. El ícono usado en el botón de "Calendario" es diferente. El ícono usado en el perfil de usuario es diferente.

**Resultado Esperado:**

Se espera que al ingresar a la app deba verse el diseño original y las tipografías  adecuadas. Igualmente se espera que la imagen del logo se ajuste al tamaño del contenedor en la sección de eventos. Así mismo se espera que los íconos mencionados sean correctos.

Se realizarán los siguientes cambios:

1. El texto utilizado en el nombre y el texto "Hola" no es correcto, debería ser: "Helvetica Now Text, Extra Bold"
2. El código de membresía usa el mismo: "Helvetica Now Text, Regular."
3. El estado de la membresía no tiene la fuente. Tampoco debe manejar: Visby, Regular
4. El texto de la fecha de vencimiento de la membresía debe ser: "Helvetica Now Text, Regular".
5. El texto del "Evento" debe tener una fuente diferente: "Helvetica Now Text, Extra Bold".
6. El ícono utilizado en el botón de calendario es diferente.
7. El ícono utilizado en el perfil de usuario es diferente.

*Tamaño de pantalla:* (Toda la pantalla)

### Capturas de pantalla
![imagen](https://user-images.githubusercontent.com/4030477/175394595-6b40937a-5bf6-410c-8c50-94629a3032b9.png)
![imagen](https://user-images.githubusercontent.com/4030477/175394623-f0ab6af4-7942-4a4d-b776-5caeb9cb59f3.png)
![imagen](https://user-images.githubusercontent.com/4030477/175394654-cc7ceb88-86cd-4baa-b737-053c35a69a82.png)
![imagen](https://user-images.githubusercontent.com/4030477/175395114-b22a9cc8-8a69-4ed8-be9c-802d6dadf54d.png)
![imagen](https://user-images.githubusercontent.com/4030477/175396657-114fb671-e0e1-4f06-bad4-1c5a42e8f7d7.png)

Original

![imagen](https://user-images.githubusercontent.com/4030477/175398857-4860dd51-8e90-45ad-97b7-ce65d977c6fb.png)

### Lista de Verificación:

- [ ] Cambie las fuentes en negrita y regulares según corresponda.
- [ ] Cambiar los íconos de: Perfil y Calendario.
- [ ] Verifique que los elementos de la lista de expectativas sean correctos.

###Referencias:
**Diseño:** https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/59d91cd4-7a13-4964-b884-4684a13c23dc/specs/
 **Nuestro:** https://deploy-preview-51--did-app.netlify.app/

**Comment by angelik0828** [comment]
When performing the verification, the text and color styles that are in the XD reference were found.

![image](https://user-images.githubusercontent.com/4030477/178312435-36aea9c5-50e0-4d60-95a9-725e1bfde8c6.png)
![image](https://user-images.githubusercontent.com/4030477/178312479-a4a0fd3a-3393-47d8-8fe8-c476574ac887.png)
![image](https://user-images.githubusercontent.com/4030477/178312510-d73b612f-7712-4396-b2cc-aeed220424b5.png)
 @victor-heliomar

**Comment by heliomar-pena** [comment]
Confirmed that works on #63
