### ISSUE TITLE
No Result In Suppliers  /  Sin Resultado En Proveedores

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-app#57]
The cart was verified and we found the following:

1. Add products.
2. Delete products.
3. Redirect to provider.
4. Validation is done by placing the number 0 in the list of products, displaying a message and informing the User that this quantity is not valid.
5. When placing a larger number that exceeds the stock or the quantity allowed for that product, a message will be displayed to the user informing that it is not possible due to inventory.
6. By clicking on "Consult", you go to the provider's WhatsApp.
7. Clicking the "Back" button prompts the user to exit the cart, thus informing the user that any changes made will be lost.
8. When you add a product in the "Product List", its status changes to red, and there is a red dot on the top right of the cart icon, indicating that a product has been added.

![image](https://user-images.githubusercontent.com/4030477/176223074-67f7fcfe-c8fe-46c8-b900-6d08ba1832e5.png)
![image](https://user-images.githubusercontent.com/4030477/176223576-04e4660f-9011-47b8-8d33-4dc4aad0636d.png)
![image](https://user-images.githubusercontent.com/4030477/176226986-aad44498-a24c-49bf-9843-94f49d760ea1.png)

When entering the providers view we found the following:

1. The offered products appear.
**two. The search box appears. When performing the search, no results appear,
 but a progress appears for a few seconds, it disappears and there is no result or message indicating the step**
3. When pressing + - ,the user should have the option to add or remove.

**Current Result:**

When performing a search it does not show search results.

**Expected Result:**

The result must be displayed or the user informed of what happened if there was no result.

![image](https://user-images.githubusercontent.com/4030477/176241743-28e0955c-877c-4505-bdf2-145e8cddc17a.png)

![image](https://user-images.githubusercontent.com/4030477/176228482-3cc14bec-6073-4fee-8e89-08087e45a45e.png)

_Originally posted by @angelik0828 at https://github.com/Azordev/did-app/issues/51#issuecomment-1168995830_

---

# Spanish Version:

Se realizó la verificación del el carrito y encontramos lo siguiente:

1. Agregar productos.
2. Eliminar productos.
3. Redirigir al proveedor.
4. La validación se realiza colocando el número 0 en la lista de productos, desplegando un mensaje e informando al Usuario que esta cantidad no es válida.
5. Al colocar un número mayor que exceda el stock o la cantidad permitida para ese producto, se mostrará un mensaje al usuario informando que no es posible por inventario.
6. Cuando se da clic en "Consultar", este va al WhatsApp del proveedor.
7. Al hacer clic en el botón "Atrás", pregunta si desea salir del carrito, informando así al usuario que se perderán los cambios realizados.
8. Al agregar un producto en la "Lista de productos", cambia su estado, pasando a ser rojo, y en la parte superior derecha del ícono del carrito hay un punto rojo que indica que se agregó un producto.

![imagen](https://user-images.githubusercontent.com/4030477/176223074-67f7fcfe-c8fe-46c8-b900-6d08ba1832e5.png)
![imagen](https://user-images.githubusercontent.com/4030477/176223576-04e4660f-9011-47b8-8d33-4dc4aad0636d.png)
![imagen](https://user-images.githubusercontent.com/4030477/176226986-aad44498-a24c-49bf-9843-94f49d760ea1.png)

Al entrar en la vista de proveedores:

1. Salen los productos ofertados.
**2. Aparece el cuadro de búsqueda. Al realizar la búsqueda no aparece ningún resultado, 
 sino que aparece un progreso por unos segundos, desaparece y no aparece ningún resultado o mensaje indicando paso**
3. Al presionar + -, el usuario debería tener la opción de agregar o quitar.

**Resultado Actual:**

Al realizar una búsqueda, no muestra resultados de búsqueda.

**Resultado Esperado:**

Se debe mostrar el resultado o informar al usuario de lo que ha sucedido en caso de que no haya resultado.

![imagen](https://user-images.githubusercontent.com/4030477/176241743-28e0955c-877c-4505-bdf2-145e8cddc17a.png)

![imagen](https://user-images.githubusercontent.com/4030477/176228482-3cc14bec-6073-4fee-8e89-08087e45a45e.png)

_Publicado originalmente por @angelik0828 en https://github.com/Azordev/did-app/issues/51#issuecomment-1168995830_

**Comment by heliomar-pena** [comment]
Confirmed that works on #63
