### ISSUE TITLE
+ And - Button Functionality  /  Funcionalidad De Los Botones + -

### ISSUE THREAD

**Issue by angelik0828** [Azordev/did-app#58]
The cart verification was performed and we found the following:

1. Add products.
2. Delete products.
3. Redirect to provider.
4. Validation is done by placing the number 0 in the list of products, displaying a message and informing the user that this quantity is not valid.
5. When placing a larger number that exceeds the stock or the quantity allowed for that product, a message is displayed to the user informing that it is not possible due to inventory.
6. When you "click" on "consult this", you go to the provider's WhatsApp.
7. By "clicking" on the "Back" button, it asks if you want to exit the cart, thus informing the user that the changes made will be lost.
8. When adding a product in the "Product List", its status changes to red, and on the top right of the cart icon there is a red dot indicating that a product has been added.

![image](https://user-images.githubusercontent.com/4030477/176223074-67f7fcfe-c8fe-46c8-b900-6d08ba1832e5.png)
![image](https://user-images.githubusercontent.com/4030477/176223576-04e4660f-9011-47b8-8d33-4dc4aad0636d.png)
![image](https://user-images.githubusercontent.com/4030477/176226986-aad44498-a24c-49bf-9843-94f49d760ea1.png)

When entering the view of providers we observed the following:

1. When the offered products come out.
2. When performing the search, no results appear, only a progress appears for a few seconds, it disappears and no results or message indicating the step appear.
3. Pressing + and - should give the user the option to add or remove.

**Current Result:**
Being in "Cart View", it does not allow adding or removing with the + and - icons

**Expected result:**

It is expected that when entering "remove or add" in the shopping cart, the buttons will work correctly.

- Inform whether or not it can be added by inventory if the quantity exceeds the limit.

![image](https://user-images.githubusercontent.com/4030477/176241743-28e0955c-877c-4505-bdf2-145e8cddc17a.png)

![image](https://user-images.githubusercontent.com/4030477/176228482-3cc14bec-6073-4fee-8e89-08087e45a45e.png)

### Check list:

- [ ] Show the functionality of the + and - buttons as appropriate.

_Originally posted by @angelik0828 at https://github.com/Azordev/did-app/issues/51#issuecomment-1168995830_
---

# Spanish Version:

Se realizó la verificación del carrito y encontramos lo siguiente:

1. Agregar productos.
2. Eliminar productos.
3. Redirigir al proveedor.
4. La validación se realiza colocando el número 0 en la lista de productos, desplegando un mensaje e informando al usuario que esta cantidad no es válida.
5. Al colocar un número mayor que exceda el stock o la cantidad permitida para ese producto, se muestra un mensaje al usuario informando que no es posible por inventario.
6. Cuando se hace "clic" en "consultar esto", se va al WhatsApp del proveedor.
7. Al hacer "clic" en el botón "Atrás", pregunta si desea salir del carrito, informando así al usuario que se perderán los cambios realizados.
8. Al agregar un producto en la "Lista de productos", cambia su estado, pasando a ser rojo, y en la parte superior derecha del ícono del carrito hay un punto rojo que indica que se agregó un producto.

![imagen](https://user-images.githubusercontent.com/4030477/176223074-67f7fcfe-c8fe-46c8-b900-6d08ba1832e5.png)
![imagen](https://user-images.githubusercontent.com/4030477/176223576-04e4660f-9011-47b8-8d33-4dc4aad0636d.png)
![imagen](https://user-images.githubusercontent.com/4030477/176226986-aad44498-a24c-49bf-9843-94f49d760ea1.png)

Al entrar en la vista de proveedores observamos lo siguiente:

1. Cuando salen los productos ofertados.
2. Al realizar la búsqueda no aparece ningún resultado, solo aparece un progreso durante unos segundos, desaparece y no aparece ningún resultado o mensaje indicando el paso.
3. Al presionar + y -, el usuario debería tener la opción de agregar o quitar.

**Resultado Actual:**
Al estar en "Vista de carrito", no permite agregar o quitar con los íconos + y -

**Resultado Esperado:**

Se espera que cuando se ingrese para "eliminar o agregar" en el carrito de compras, los botones  funcionen correctamente.

- Informar si se puede o no agregar por inventario si la cantidad supera el límite.

![imagen](https://user-images.githubusercontent.com/4030477/176241743-28e0955c-877c-4505-bdf2-145e8cddc17a.png)

![imagen](https://user-images.githubusercontent.com/4030477/176228482-3cc14bec-6073-4fee-8e89-08087e45a45e.png)

### Lista de Verificación:

- [ ] Mostrar la funcionalidad de los botones + y - según corresponda.

_Publicado originalmente por @angelik0828 en https://github.com/Azordev/did-app/issues/51#issuecomment-1168995830_

**Comment by Israel-Laguan** [comment]
@victor-heliomar I updated a product (1c62427a-be79-40fd-9476-75ceb08d3681) with 5 items so this issue can be tested

**Comment by heliomar-pena** [comment]
@Israel-Laguan @angelik0828 I made some tests on my cellphone
 
[!video](https://user-images.githubusercontent.com/66505715/178567834-7b4a7a12-a4fa-4a87-bbc6-f2adcb6adf3c.mp4)

**Comment by heliomar-pena** [comment]
Confirmed that works on #63
