### ISSUE TITLE
Create Event Detail View  /  Crear Vista Detallada Del Evento.

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#6]
**Explanation:**

The idea with this view is to allow the user to access more detailed information about the event of their choice. Details about the event are as follows:

1. Description of the event.
2. Date and time of the event.
3. Address of the place where the event will take place.
4. An image of the event.
5. Name of the event.
6. Participate button.

**Checklist:**

- [x] As a user, I would like to see a detailed description of the event to know what it is about.
- [x] As a user, I would like to see the date of the event in order to attend.
- [ ] As a user, I need to know the description of the address where the event will take place in order to attend.
- [x] As a member, I want to see images related to the event to have a reference of it.
- [x] As a user, I would need to know the name of the event.
- [ ] As a user, I would like to be able to reserve my participation in the event.

### Dependencies:

It has no dependencies.

###Referencies:

- [Google Calendar API](https://developers.google.com/calendar/api)
- https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/c2ecea46-90e6-466e-b14c-1e1db4165d65?hints=off
-

### Screenshot:
![DID 5](https://user-images.githubusercontent.com/98891182/170330020-31982ad9-2240-49b0-b773-9706f1eac789.png)

### Workflow:
Access. Main Screen- Events- Specific Event.

Spanish Version:

**Explicación:**
La idea con esta vista es permitirle al usuario acceder a una información más detallada sobre el evento de su preferencia. Los detalles sobre el evento son los siguientes:

1. Descripción del evento.
2. Fecha y hora del evento.
3. Dirección del lugar donde se realizará el evento.
4. Una imagen del evento.
5. Nombre del evento.
6. Botón de participar.

**Lista de Verificación:**

- [x]  Como usuario, quisiera ver una descripción detallada del evento para conocer de qué se trata.
- [x] Como usuario, me gustaría ver la fecha del evento para poder asistir.
- [ ] Como usuario, necesito conocer la descripción de la dirección donde se realizará el evento para poder asistir.
- [x] Como miembro, deseo ver imágenes referentes al evento para tener una referencia del mismo.
- [x] Como usuario,  necesitaría conocer el nombre del evento.
- [ ] Como usuario, me gustaría poder reservar mi participación en el evento.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:
No tiene dependencias.

### Referencias:
- [Google Calendar API](https://developers.google.com/calendar/api)
- https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/c2ecea46-90e6-466e-b14c-1e1db4165d65?hints=off

 ### Captura de pantalla:
![DID 5](https://user-images.githubusercontent.com/98891182/170330251-ba91643a-628c-4a5f-b768-51547bbb0725.png)

### Flujo de trabajo:
Acceso. pantalla principal- eventos- evento específico.

**Comment by CARPER11** [comment]
he añadido dos historias faltantes el boton de participar y el nombre del evento. Gracias

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar, y ampliacion de alguna historia de usuario por favor revisar..
Gracias de antemano.

**Comment by heliomar-pena** [comment]
The design doesn't include the address and time where the event is, I'm not sure where should I to add it

**Comment by heliomar-pena** [comment]
The task:

`As a user, I would like to be able to reserve my participation in the event.`

I think is covered here: #26 

And the task:

`As a user, I need to know the description of the address where the event will take place in order to attend.`

Is not covered in the current design.

I think to avoid blocking the rest of task of this issue we could to create a new issue to add the address and time of event in some place of the APP
