### ISSUE TITLE
Search By Event Title  /  Búsqueda Por Título Del Evento

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#7]
**Explanation:**

The objective of this task is to be able to search for the available events in the event list by means of a text bar.

**User story to fulfill:**

- [ ] As a user, I want to be able to place the title of the event in a text bar to be able to filter them.

### Dependencies:
- [x] #3 

### References:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/50ab662a-b54a-47ea-b30a-f0299164d0c1?hints=off

### Screenshot:
![DID 4](https://user-images.githubusercontent.com/98891182/170301994-2aca5c2d-3afe-49df-a8af-d603bdc1ebfd.png)

### Workflow:
Access- Main Screen-Events

Spanish Version:

**Explicación:**
El objetivo de esta tarea es poder buscar los eventos disponibles de la lista de eventos por medio de una barra de texto.

**Historia de usuario a cumplir:**

- [ ]  Como usuario, deseo poder colocar el título del evento en una barra de texto para poder filtrarlos.

**Checklist de casos de uso QA:**
- [ ]

**Checklist tareas técnicas**
- [ ]

### Dependencias:

- [x] #3 

### Referencias:
https://xd.adobe.com/view/a3457990-d0e6-4f82-876a-f382a7c73582-f616/screen/50ab662a-b54a-47ea-b30a-f0299164d0c1?hints=off

### Captura de pantalla
![DID 4](https://user-images.githubusercontent.com/98891182/170301357-e4f5b660-f464-46c7-bd95-480ae1c167c9.png)

### Flujo de Trabajo:
Acceso- Pantalla Principal-Eventos.

**Comment by angelik0828** [comment]
@CARPER11  tengo una duda, no se si la palabra sea correcta, por que estas haciendo una búsqueda, no filtro, creo que abrían mas de una opción y podrían quitarse y ponerse.

**Comment by CARPER11** [comment]
@angelik0828 vale ya cambiado de filtro a busqueda.

**Comment by anaceciliamolinares** [comment]
CARPER11, no sé si este issue lleva las sigts características de los demás. Pero le faltan: 1. Historia de usuario a cumplir. 2. Dependencias. 3. Referencias. 4. Flujo de trabajo. Verificar , por favor.

**Comment by CARPER11** [comment]
[SPIKE] Analizar casos de uso y manejo de errores posibles para añadir en la Checklist por favor @angelik0828 
[SPIKE] Comentar las tareas técnicas para desarrollar la funcionalidad, por favor @e-azocar 
[SPIKE] Añadir los casos de uso y tareas técnicas a las Checklist correspondientes.
[SPIKE] sugerir en caso de que lo crean pertinente convertir alguna historia de usuario en una tarea secundaria, @angelik0828 @e-azocar 
@anaceciliamolinares he realizado algunos cambios menores como añadir Checklist de casos de uso y Checklist de tareas técnicas ambos por completar.
Gracias de antemano.

**Comment by heliomar-pena** [comment]
At the last design this feature was removed

![image](https://user-images.githubusercontent.com/66505715/178611930-17a19f42-d7a2-4ead-aa10-31b44827ab6b.png)
