### ISSUE TITLE
Agendar eventos

### ISSUE THREAD

**Issue by CARPER11** [Azordev/did-app#8]
**Explicación**
La opción de agendar evento le permitirá al usuario poder integrar los eventos de la aplicación con google calendar, de esta manera podrá verlos en su agenda personal de calendar.

**Checklist**

- [ ]  Como usuario quiero agendar los eventos disponibles para verlos en google calendar.

### Dependencies

- [x] #3

**Comment by Israel-Laguan** [comment]
@Katsu08 @e-azocar is this possible using Google Calendar in the app

**Comment by e-azocar** [comment]
> @Katsu08 @e-azocar is this possible using Google Calendar in the app

I need to investigate more about this, I'm not sure

**Comment by heliomar-pena** [comment]
Always that the user was a member or guest of the event, they will see the event in their Google Calendar.

I think it's possible if we can edit the event to add participants <-

@e-azocar @Israel-Laguan

**Comment by angelik0828** [comment]
the user can confirm attendance?

**Comment by Israel-Laguan** [comment]
As far as I know, creating events using Google Calendar is not available, rather we should use our backend for it.

**Comment by heliomar-pena** [comment]
This task is out to date, needs to be added the new changes about Google Calendar

**Comment by heliomar-pena** [comment]
Or maybe add another task and close this? @CARPER11 what do you think?

**Comment by heliomar-pena** [comment]
Currently is fine with the Calendar view in the APP, I think this task is not needed, reopen it if is needed
